name: Automation Pipeline

permissions:
  contents: write

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        run: |
          npm install newman xml2js
      
      - name: Install Newman HTML reporter
        run: |
          npm install -g newman-reporter-htmlextra
      
      - name: Run API Smoke Tests
        run: |
            newman run src/test/api/api-smoke-tests.json \
            --reporters cli,json,htmlextra \
            --reporter-json-export docs/smoke-report.json \ 
            --reporter-htmlextra-export docs/smoke-report.html \
            --color on \
            --verbose

      - name: Start Test API Server
        run: |
          node server.js &
          sleep 3

      - name: Run Load Tests
        run: node src/test/api/loadTest.js

      - name: Run Selenium Tests
        run: mvn test

      - name: Build unified report
        run: node src/test/resources/buildReport.js

      - name: Commit report to repo
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git diff --staged --quiet || git commit -m "Update QA automation report"
          git push origin HEAD:main
